FilmTicketApp/Models/Producer.cs
using FilmTicketApp.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace FilmTicketApp.Models
{
   public class Producer: IEntityBase
   {
      [Key]
      public int Id { get; set; }

      [Display(Name = "Profile Picture")]
      [Required(ErrorMessage = "Profile picture is required")]
      public string ProfilePicture { get; set; }

      [Display(Name = "Full Name")]
      [Required(ErrorMessage = "Full Name is required")]
      public string FullName { get; set; }

      [Display(Name = "Biography")]
      [Required(ErrorMessage = "Biographyis required")]
      public string Biography { get; set; }

      public List<Film>? Films { get; set; }  

   }
}

FilmTicketApp/Controllers/ProducersController.cs
using FilmTicketApp.Data;
using FilmTicketApp.Data.Services;
using FilmTicketApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace FilmTicketApp.Controllers
{
   public class ProducersController : Controller
   {
      private readonly IProducersService _producersService;

      public ProducersController(IProducersService producersService)
      {
         _producersService = producersService;
      }

      public async Task<IActionResult> Index()
      {
         var data = await _producersService.GetAll();
         return View(data);
      }

      public async Task<IActionResult> Details(int id)
      {
         var producerDetails = await _producersService.GetById(id);

         if (producerDetails == null)
         {
            return View("NotFound");
         }

         return View(producerDetails);
      }

      public async Task<IActionResult> Create() 
      {
         return View();
      }

      [HttpPost]
      public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Biography")] Producer producer)
      {
         if(!ModelState.IsValid)
         {
            return View(producer);
         }

         await _producersService.Add(producer);

         return RedirectToAction(nameof(Index));
      }

      public async Task<IActionResult> Edit(int id)
      {
         var details = await _producersService.GetById(id);

         if (details == null)
         {
            return View("NotFound");
         }

         return View(details);
      }

      [HttpPost]
      public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePicture,Biography")] Producer producer)
      {
         if (!ModelState.IsValid)
         {
            return View(producer);
         }

         if(id == producer.Id)
         {
            await _producersService.Update(id, producer);

            return RedirectToAction(nameof(Index));
         }

         return View(producer);
      }

      public async Task<IActionResult> Delete(int id)
      {
         var details = await _producersService.GetById(id);

         if (details == null)
         {
            return View("NotFound");
         }

         return View(details);
      }

      [HttpPost, ActionName("Delete")]
      public async Task<IActionResult> DeleteConfirmed(int id)
      {
         Producer producerDetails = _producersService.GetById(id).Result;
         if (producerDetails == null)
            return View(this);

         await _producersService.Delete(id);

         return RedirectToAction(nameof(Index));
      }
   }
}

FilmTicketApp/Views/Producers/Create.cshtml
@model Producer

@{
    ViewData["Title"] = "Add a new Producer";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add new Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" />

                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Biography" class="control-label"></label>
                        <input asp-for="Biography" class="form-control" />
                        <span asp-validation-for="Biography" class="text-danger"></span>
                    </div>

                    <div>
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index"> Show All</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function ()
        {
            var output = document.getElementById('ProfilePicturePreview');
               output.src = $("ProfilePicture").val();
        })

         $("#ProfilePicture").on("change", function()
         {
             var output = document.getElementById('ProfilePicturePreview');
             output.src = $(this).val();
         }
    </script>
}

FilmTicketApp/Views/Producers/Delete.cshtml
@model Producer



<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
               
                <div class="form-group text-center">
                    <img id="ProfilePicturePreview" />

                </div>
                <div class="form-group">
                    <label asp-for="ProfilePicture" class="control-label"></label>
                    <input asp-for="ProfilePicture" class="form-control" readonly/>
                    <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" readonly/>
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Biography" class="control-label"></label>
                    <input asp-for="Biography" class="form-control" readonly/>
                    <span asp-validation-for="Biography" class="text-danger"></span>
                </div>

                <div class="form-group">

                   <form action="Delete" method="post">
                      <input type="hidden" asp-for="Id"/>
                      <input type="submit" value="Confirmn" class="btn-danger float-right"/>
                   </form>

                    <a class="btn btn-outline-secondary" 
                                 asp-action="Index"> Show All</a>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function ()
        {
            var output = document.getElementById('ProfilePicturePreview');
               output.src = $("ProfilePicture").val();
        })

    </script>
}

FilmTicketApp/Views/Producers/Details.cshtml
@model Producer



<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <div class="form-group text-center">
                    <img id="ProfilePicturePreview" />

                </div>
                <div class="form-group">
                    <label asp-for="ProfilePicture" class="control-label"></label>
                    <input asp-for="ProfilePicture" class="form-control" readonly />
                    <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" readonly />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Biography" class="control-label"></label>
                    <input asp-for="Biography" class="form-control" readonly />
                    <span asp-validation-for="Biography" class="text-danger"></span>
                </div>

                <div>
                    <a class="btn btn-outline-success float-right"
                       asp-action="Edit"
                       asp-route-id="@Model.Id"> Edit</a>
                    <a class="btn btn-outline-secondary"
                       asp-action="Index"> Show All</a>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function ()
        {
            var output = document.getElementById('ProfilePicturePreview');
               output.src = $("ProfilePicture").val();
        })

    </script>
}

FilmTicketApp/Views/Producers/Edit.cshtml
@model Producer

@{
    ViewData["Title"] = "Edit an Producer";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" />

                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Biography" class="control-label"></label>
                        <input asp-for="Biography" class="form-control" />
                        <span asp-validation-for="Biography" class="text-danger"></span>
                    </div>

                    <div>
                        <input type="submit" value="Update" asp-route-id="@Model.Id" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index"> Show All</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
       $(document).ready(function ()
       {
           var output = document.getElementById('ProfilePicturePreview');
              output.src = $("ProfilePicture").val();
       })

        $("#ProfilePicture").on("change", function()
        {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        }
    </script>
}

FilmTicketApp/Views/Producers/Index.cshtml
@*Define model*@
@model IEnumerable<Producer>

@*Define ViewData*@

@{
    ViewData["Title"] = "List of Producers";
}

@*Write Code*@

<h1>
    Welcome to Actors view
</h1>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePicture)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Biography)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePicture" style="max-width:150px" />
                        </td>

                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>

                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Biography)
                        </td>

                        <td class="align-middle">

                            <a class="btn btn-outline-primary"
                                 asp-action="Edit"
                                 asp-route-id="@item.Id">
                                <i class="bi bi-pencil-square">Edit</i>
                            </a> |

                            <a class="btn btn-outline-info"
                               asp-action="Details"
                               asp-route-id="@item.Id">
                                <i class="bi bi-pencil-eye">Details</i>
                            </a> |

                            <a class="btn btn-danger"
                                 asp-action="Delete"
                                 asp-route-id="@item.Id">
                                <i class="bi bi-trash">Delete</i>
                            </a>

                        </td>
                    </tr>
                }
            </tbody>

        </table>

    </div>
</div>

<div class="text-white">
    <a asp-controller="Producers" asp-action="Create" class="btn btn-success">
        <i class="bi bu-plus-circle">
            Add new
        </i>
    </a>

</div>